### ISSUE TITLE
Update quickstart

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/deeplearning4j-docs#34]
## Due Date
*To be completed by:* 2018-04-20

## Description
Because of changes in DL4J v1.0, our quickstart needs to be updated. This issue also serves as a general issue for our quickstart migration to use a notebook to walk the user through features.

See also: https://github.com/deeplearning4j/deeplearning4j-docs/issues/32

**Comment by crockpotveggies** [comment]
Now in progress. Working on a new Quickstart notebook and will be working with @wmeddie to ensure our tutorials are bundled in the SKIL-CE docker image. We will point users to download the docker and run tutorials from there.

**Comment by ShamsUlAzeem** [comment]
@crockpotveggies make sure the docker updates are tagged. Something like skymindops/skil-ce:tutorials and they are in separate folders in this repository -> https://github.com/SkymindIO/skil-docker

The reason for this is to keep the documentation consistent, since some of the images work for ECS, AKS and EKS and some don't. You can build on top of the base image: https://github.com/SkymindIO/skil-docker/tree/master/skil-base

**Comment by wmeddie** [comment]
@ShamsUlAzeem These would be part of the 1.1.0 release not a separate docker image.

**Comment by ShamsUlAzeem** [comment]
@wmeddie Okay. Are we going to use SkilContext in the bundled notebooks? If so, have we found any workaround for using skilcontext without experiments? Or are we going to have pre-seeded experiments and workspaces in skil's database and later connect the notebooks to it?

**Comment by crockpotveggies** [comment]
Note to self: Add a paragraph about *why* the user should use SKIL-CE versus a Maven Archetype/Giter8 template. Mainly about having deployment hand-in-hand with training code.
